### ISSUE TITLE
Locale-sensitive conversion of value parameters

### ISSUE THREAD

**Issue by akbertram** [hannesmuehleisen/renjin-dbi#6]
At some point in the code, parameters to an insert statement are converted from double to string using locale-sensitive formatting:

Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:

```
INSERT INTO renjintest VALUES (5,1, 3,5, 1,4, 0,2, 'setosa'), (4,9, 3, 1,4, 0,2, 'setosa'), (4,7, 
```

**Comment by ebocher** [comment]
The best way  is to follow the SQL syntax rules and not locale settings.  The syntax saids that you must used a . as a decimal separator.

**Comment by ebocher** [comment]
I don't know if it's the good place but I modified .bindParameter in DBI.R with

``` R
From
else if (valueClass %in% c("numeric", "logical", "integer"))
            statement <- sub("?", value, statement, fixed=TRUE)

To
else if (valueClass %in% c("numeric", "logical", "integer"))
            statement <- sub("?", sub(",", ".",value), statement, fixed=TRUE)


```

**Comment by ebocher** [comment]
Pushed at https://github.com/ebocher/renjin-dbi/tree/RH2_module

**Comment by ebocher** [comment]
This issue is solved.

**Comment by ebocher** [comment]
This is issue can be closed.
